Repository community-scripts/ProxmoxVED, pull requests merged in 2025-05, with the labels that each got.

#198 JumpServer
  ct/jumpserver.sh
  frontend/public/json/jumpserver.json
  install/jumpserver-install.sh
Labels: new script, website

#305 Revert "Delete Files for streamlink-webui after Merge to Main"
  ct/streamlink-webui.sh
  frontend/public/json/streamlink-webui.json
  install/streamlink-webui-install.sh
Labels: new script, website

#365 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, maintenance

#316 New Script: Backrest
  ct/backrest.sh
  frontend/public/json/backrest.json
  install/backrest-install.sh
Labels: new script, website

#401 Add install script for configarr
  ct/configarr.sh
  frontend/public/json/configarr.json
  install/configarr-install.sh
Labels: new script, website

#303 Add garmin-grafana LXC script
  ct/garmin-grafana.sh
  frontend/public/json/garmin-grafana.json
  install/garmin-grafana-install.sh
Labels: new script, website

#416 New Script: Kasm
  ct/kasm.sh
  frontend/public/json/kasm.json
  install/kasm-install.sh
Labels: documentation, new script, website, maintenance, update script

#438 New Script: Lyrion Music Server
  ct/lyrionmusicserver.sh
  frontend/public/json/lyrionmusicserver.json
  install/lyrionmusicserver-install.sh
Labels: new script, website, update script

#459 NIC offloading fix
  frontend/public/json/nic-offloading-fix.json
  tools/pve/nic-offloading-fix.sh
Labels: website, feature
