Repository community-scripts/ProxmoxVED, pull requests merged in 2025-03, with the labels that each got.

#1 New Script: Seafile
  ct/seafile.sh
  install/seafile-install.sh
  json/seafile.json
Labels: new script, website

#2 Fix Seafile script missing admin account creation
  install/seafile-install.sh
Labels: update script

#22 New Script: Wazuh
  ct/wazuh.sh
  install/wazuh-install.sh
  json/wazuh.json
Labels: new script, website

#51 Discord WF
  .github/workflows/archive-discord-thread.yml
  .github/workflows/create-discord-thread.yml
Labels: maintenance, feature, github

#32 Added FreePBX installation script
  ct/freepbx.sh
  install/freepbx-install.sh
  json/freepbx.json
Labels: new script, website

#89 initial install for openziti tunnel
  ct/openziti-tunnel.sh
  frontend/public/json/openziti-tunnel.json
  install/openziti-tunnel-install.sh
Labels: new script, website

#115 Big Change: Use curl instead of wget
  .github/workflows/create-ready-for-testing-message.yml
  .github/workflows/scripts/app-test/pr-build.func
  ct/Deferred/documenso.sh
  ct/Deferred/hoodik.sh
  ct/Deferred/koel.sh
  ct/Deferred/maxun.sh
  ct/Deferred/nginxproxymanager.sh
  ct/Deferred/pixelfed.sh
  ct/Deferred/roundcubemail.sh
  ct/calibre-web-automated.sh
  ct/fileflows.sh
  ct/meilisearch.sh
  ct/qbittorrent.sh
  ct/slskd.sh
  docs/ct/AppName.md
  docs/install/AppName-install.md
  docs/install/AppName-install.sh
  frontend/src/app/scripts/_components/ScriptItems/InstallCommand.tsx
  install/calibre-web-automated-install.sh
  install/docspell-install.sh
  install/fileflows-install.sh
  install/freepbx-install.sh
  install/frigate-install.sh
  install/healthchecks-install.sh
  install/manyfold-install.sh
  install/meilisearch-install.sh
  install/qbittorrent-install.sh
  install/slskd-install.sh
  install/wazuh-install.sh
  misc/build.func
  misc/install.func
  scripts/tools/filebrowser.sh
  scripts/tools/frigate-support.sh
  scripts/tools/hw-acceleration.sh
  scripts/vms/debian-vm-test-helper.sh
  scripts/vms/debian-vm.sh
Labels: website, update script, maintenance, core, high risk, feature, github, breaking change

#143 correct path in update script function
  ct/openziti-tunnel.sh
Labels: update script, bugfix

#147 Update var in CT files
  ct/Deferred/ampache.sh
  ct/Deferred/babybuddy.sh
  ct/Deferred/documenso.sh
  ct/Deferred/ghostfolio.sh
  ct/Deferred/hoodik.sh
  ct/Deferred/koel.sh
  ct/Deferred/mattermost.sh
  ct/Deferred/netbootxyz.sh
  ct/Deferred/nginxproxymanager.sh
  ct/Deferred/pixelfed.sh
  ct/Deferred/roundcubemail.sh
  ct/Deferred/squirrelserversmanager.sh
  ct/Deferred/timescaledb.sh
  ct/Deferred/wallabag.sh
  ct/alpine-gitea.sh
  ct/alpine-mariadb.sh
  ct/alpine-node-red.sh
  ct/alpine-postgresql.sh
  ct/alpine-prometheus.sh
  ct/alpine-tinyauth.sh
  ct/alpine-wireguard.sh
  ct/alpine.sh
  ct/docspell.sh
  ct/freepbx.sh
  ct/frigate.sh
  ct/fumadocs.sh
  ct/healthchecks.sh
  ct/librenms.sh
  ct/manyfold.sh
  ct/maxun.sh
  ct/meilisearch.sh
  ct/openproject.sh
  ct/openziti-tunnel.sh
  ct/polaris.sh
  ct/reactive-resume.sh
  ct/slskd.sh
  ct/ubuntu.sh
Labels: update script

#140 initial version of openziti-controller install
  ct/openziti-controller.sh
  frontend/public/json/openziti-controller.json
  install/openziti-controller-install.sh
Labels: new script, website, update script

#159 add ip address output
  ct/openziti-tunnel.sh
Labels: update script, bugfix
