Repository community-scripts/ProxmoxVED, pull requests merged in 2025-09, with the labels that each got.

#796 Livebook
  ct/livebook.sh
  frontend/public/json/livebook.json
  install/livebook-install.sh
Labels: update script, new script, website, maintenance, core, high risk, feature

#902 ct: add Alpine Linux Caddy
  ct/alpine-caddy.sh
  ct/headers/alpine-caddy
  frontend/public/json/caddy.json
  install/alpine-caddy-install.sh
Labels: new script, website

#918 Fix alpine-ntfy
  ct/alpine-ntfy.sh
  install/alpine-ntfy-install.sh
Labels: update script

#929 Support for Frigate v0.16
  ct/frigate.sh
  install/frigate-install.sh
Labels: update script, bugfix
