Repository community-scripts/ProxmoxVED, pull requests merged in 2025-04, with the labels that each got.

#162 Fix for freepbx-install.sh
  install/freepbx-install.sh
Labels: update script, bugfix

#214 Add new script UmlautAdaptarr
  ct/umlautadaptarr.sh
  frontend/public/json/umlautadaptarr.json
  install/umlautadaptarr-install.sh
Labels: new script, website

#226 Test Discussion WF
  ct/test_wf.sh
Labels: new script

#237 New script: Librespeed
  ct/librespeed.sh
  frontend/public/json/librespeed.json
  install/librespeed-install.sh
Labels: new script, website

#230 Cloudflare-DDNS
  ct/cloudflare-ddns.sh
  frontend/public/json/cloudflare-ddns.json
  install/cloudflare-ddns-install.sh
Labels: new script, website
